run-dist:
	./build/install/app/bin/app

clean:
	gradle clean

build:
	gradle installDist

run:
	gradle run

lint:
	gradle checkstyleMain

test:
	gradle test

report:
	gradle jacocoTestReport

.PHONY: build
