run-dist:
	./build/install/app/bin/app

clean:
	./gradlew clean

build:
	./gradlew installDist

run:
	./gradlew run

lint:
	./gradlew checkstyleMain

test:
	./gradlew test

report:
	./gradlew jacocoTestReport

.PHONY: build
